import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextuiProvider from "../providers/nextui";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FindMi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <NextuiProvider>
          <div className="light text-foreground bg-background w-screen h-screen flex flex-col-reverse lg:flex-col">
            {children}{" "}
          </div>
        </NextuiProvider>
      </body>
    </html>
  );
}
